// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Server.proto

package com.stone.proto;

public final class Servers {
  private Servers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ServerType}
   *
   * <pre>
   * serverType
   * </pre>
   */
  public enum ServerType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GATE = 1;</code>
     */
    GATE(0, 1),
    /**
     * <code>GAME = 2;</code>
     */
    GAME(1, 2),
    /**
     * <code>WORLD = 3;</code>
     */
    WORLD(2, 3),
    /**
     * <code>DB = 4;</code>
     */
    DB(3, 4),
    /**
     * <code>CROSS = 5;</code>
     */
    CROSS(4, 5),
    ;

    /**
     * <code>GATE = 1;</code>
     */
    public static final int GATE_VALUE = 1;
    /**
     * <code>GAME = 2;</code>
     */
    public static final int GAME_VALUE = 2;
    /**
     * <code>WORLD = 3;</code>
     */
    public static final int WORLD_VALUE = 3;
    /**
     * <code>DB = 4;</code>
     */
    public static final int DB_VALUE = 4;
    /**
     * <code>CROSS = 5;</code>
     */
    public static final int CROSS_VALUE = 5;


    public final int getNumber() { return value; }

    public static ServerType valueOf(int value) {
      switch (value) {
        case 1: return GATE;
        case 2: return GAME;
        case 3: return WORLD;
        case 4: return DB;
        case 5: return CROSS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServerType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ServerType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServerType>() {
            public ServerType findValueByNumber(int number) {
              return ServerType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.stone.proto.Servers.getDescriptor().getEnumTypes().get(0);
    }

    private static final ServerType[] VALUES = values();

    public static ServerType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ServerType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ServerType)
  }

  public interface ServerInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServerInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .ServerType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .ServerType type = 1;</code>
     */
    com.stone.proto.Servers.ServerType getType();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code ServerInfo}
   *
   * <pre>
   * serverInfo
   * </pre>
   */
  public static final class ServerInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ServerInfo)
      ServerInfoOrBuilder {
    // Use ServerInfo.newBuilder() to construct.
    private ServerInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerInfo defaultInstance;
    public static ServerInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ServerInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.stone.proto.Servers.ServerType value = com.stone.proto.Servers.ServerType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stone.proto.Servers.internal_static_ServerInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stone.proto.Servers.internal_static_ServerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stone.proto.Servers.ServerInfo.class, com.stone.proto.Servers.ServerInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerInfo> PARSER =
        new com.google.protobuf.AbstractParser<ServerInfo>() {
      public ServerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.stone.proto.Servers.ServerType type_;
    /**
     * <code>required .ServerType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ServerType type = 1;</code>
     */
    public com.stone.proto.Servers.ServerType getType() {
      return type_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = com.stone.proto.Servers.ServerType.GATE;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.stone.proto.Servers.ServerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.Servers.ServerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.Servers.ServerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.Servers.ServerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.Servers.ServerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.Servers.ServerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.stone.proto.Servers.ServerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.stone.proto.Servers.ServerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.stone.proto.Servers.ServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.Servers.ServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.stone.proto.Servers.ServerInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerInfo}
     *
     * <pre>
     * serverInfo
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServerInfo)
        com.stone.proto.Servers.ServerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stone.proto.Servers.internal_static_ServerInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stone.proto.Servers.internal_static_ServerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stone.proto.Servers.ServerInfo.class, com.stone.proto.Servers.ServerInfo.Builder.class);
      }

      // Construct using com.stone.proto.Servers.ServerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.stone.proto.Servers.ServerType.GATE;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stone.proto.Servers.internal_static_ServerInfo_descriptor;
      }

      public com.stone.proto.Servers.ServerInfo getDefaultInstanceForType() {
        return com.stone.proto.Servers.ServerInfo.getDefaultInstance();
      }

      public com.stone.proto.Servers.ServerInfo build() {
        com.stone.proto.Servers.ServerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stone.proto.Servers.ServerInfo buildPartial() {
        com.stone.proto.Servers.ServerInfo result = new com.stone.proto.Servers.ServerInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stone.proto.Servers.ServerInfo) {
          return mergeFrom((com.stone.proto.Servers.ServerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stone.proto.Servers.ServerInfo other) {
        if (other == com.stone.proto.Servers.ServerInfo.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stone.proto.Servers.ServerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stone.proto.Servers.ServerInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.stone.proto.Servers.ServerType type_ = com.stone.proto.Servers.ServerType.GATE;
      /**
       * <code>required .ServerType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ServerType type = 1;</code>
       */
      public com.stone.proto.Servers.ServerType getType() {
        return type_;
      }
      /**
       * <code>required .ServerType type = 1;</code>
       */
      public Builder setType(com.stone.proto.Servers.ServerType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ServerType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.stone.proto.Servers.ServerType.GATE;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ServerInfo)
    }

    static {
      defaultInstance = new ServerInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ServerInfo)
  }

  public interface RegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Register)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .ServerInfo info = 1;</code>
     */
    boolean hasInfo();
    /**
     * <code>required .ServerInfo info = 1;</code>
     */
    com.stone.proto.Servers.ServerInfo getInfo();
    /**
     * <code>required .ServerInfo info = 1;</code>
     */
    com.stone.proto.Servers.ServerInfoOrBuilder getInfoOrBuilder();
  }
  /**
   * Protobuf type {@code Register}
   *
   * <pre>
   * registerInfo
   * </pre>
   */
  public static final class Register extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Register)
      RegisterOrBuilder {
    // Use Register.newBuilder() to construct.
    private Register(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Register(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Register defaultInstance;
    public static Register getDefaultInstance() {
      return defaultInstance;
    }

    public Register getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Register(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.stone.proto.Servers.ServerInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(com.stone.proto.Servers.ServerInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stone.proto.Servers.internal_static_Register_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stone.proto.Servers.internal_static_Register_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stone.proto.Servers.Register.class, com.stone.proto.Servers.Register.Builder.class);
    }

    public static com.google.protobuf.Parser<Register> PARSER =
        new com.google.protobuf.AbstractParser<Register>() {
      public Register parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Register(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Register> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INFO_FIELD_NUMBER = 1;
    private com.stone.proto.Servers.ServerInfo info_;
    /**
     * <code>required .ServerInfo info = 1;</code>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ServerInfo info = 1;</code>
     */
    public com.stone.proto.Servers.ServerInfo getInfo() {
      return info_;
    }
    /**
     * <code>required .ServerInfo info = 1;</code>
     */
    public com.stone.proto.Servers.ServerInfoOrBuilder getInfoOrBuilder() {
      return info_;
    }

    private void initFields() {
      info_ = com.stone.proto.Servers.ServerInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, info_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.stone.proto.Servers.Register parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.Servers.Register parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.Servers.Register parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.Servers.Register parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.Servers.Register parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.Servers.Register parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.stone.proto.Servers.Register parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.stone.proto.Servers.Register parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.stone.proto.Servers.Register parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.Servers.Register parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.stone.proto.Servers.Register prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Register}
     *
     * <pre>
     * registerInfo
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Register)
        com.stone.proto.Servers.RegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stone.proto.Servers.internal_static_Register_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stone.proto.Servers.internal_static_Register_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stone.proto.Servers.Register.class, com.stone.proto.Servers.Register.Builder.class);
      }

      // Construct using com.stone.proto.Servers.Register.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = com.stone.proto.Servers.ServerInfo.getDefaultInstance();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stone.proto.Servers.internal_static_Register_descriptor;
      }

      public com.stone.proto.Servers.Register getDefaultInstanceForType() {
        return com.stone.proto.Servers.Register.getDefaultInstance();
      }

      public com.stone.proto.Servers.Register build() {
        com.stone.proto.Servers.Register result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stone.proto.Servers.Register buildPartial() {
        com.stone.proto.Servers.Register result = new com.stone.proto.Servers.Register(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stone.proto.Servers.Register) {
          return mergeFrom((com.stone.proto.Servers.Register)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stone.proto.Servers.Register other) {
        if (other == com.stone.proto.Servers.Register.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInfo()) {
          
          return false;
        }
        if (!getInfo().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stone.proto.Servers.Register parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stone.proto.Servers.Register) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.stone.proto.Servers.ServerInfo info_ = com.stone.proto.Servers.ServerInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.stone.proto.Servers.ServerInfo, com.stone.proto.Servers.ServerInfo.Builder, com.stone.proto.Servers.ServerInfoOrBuilder> infoBuilder_;
      /**
       * <code>required .ServerInfo info = 1;</code>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ServerInfo info = 1;</code>
       */
      public com.stone.proto.Servers.ServerInfo getInfo() {
        if (infoBuilder_ == null) {
          return info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ServerInfo info = 1;</code>
       */
      public Builder setInfo(com.stone.proto.Servers.ServerInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ServerInfo info = 1;</code>
       */
      public Builder setInfo(
          com.stone.proto.Servers.ServerInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ServerInfo info = 1;</code>
       */
      public Builder mergeInfo(com.stone.proto.Servers.ServerInfo value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              info_ != com.stone.proto.Servers.ServerInfo.getDefaultInstance()) {
            info_ =
              com.stone.proto.Servers.ServerInfo.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ServerInfo info = 1;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = com.stone.proto.Servers.ServerInfo.getDefaultInstance();
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .ServerInfo info = 1;</code>
       */
      public com.stone.proto.Servers.ServerInfo.Builder getInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ServerInfo info = 1;</code>
       */
      public com.stone.proto.Servers.ServerInfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_;
        }
      }
      /**
       * <code>required .ServerInfo info = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.stone.proto.Servers.ServerInfo, com.stone.proto.Servers.ServerInfo.Builder, com.stone.proto.Servers.ServerInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.stone.proto.Servers.ServerInfo, com.stone.proto.Servers.ServerInfo.Builder, com.stone.proto.Servers.ServerInfoOrBuilder>(
                  getInfo(),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Register)
    }

    static {
      defaultInstance = new Register(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Register)
  }

  public interface UnRegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UnRegister)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .ServerInfo info = 2;</code>
     */
    boolean hasInfo();
    /**
     * <code>required .ServerInfo info = 2;</code>
     */
    com.stone.proto.Servers.ServerInfo getInfo();
    /**
     * <code>required .ServerInfo info = 2;</code>
     */
    com.stone.proto.Servers.ServerInfoOrBuilder getInfoOrBuilder();
  }
  /**
   * Protobuf type {@code UnRegister}
   *
   * <pre>
   * unRegister
   * </pre>
   */
  public static final class UnRegister extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UnRegister)
      UnRegisterOrBuilder {
    // Use UnRegister.newBuilder() to construct.
    private UnRegister(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UnRegister(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UnRegister defaultInstance;
    public static UnRegister getDefaultInstance() {
      return defaultInstance;
    }

    public UnRegister getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UnRegister(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              com.stone.proto.Servers.ServerInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(com.stone.proto.Servers.ServerInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stone.proto.Servers.internal_static_UnRegister_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stone.proto.Servers.internal_static_UnRegister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stone.proto.Servers.UnRegister.class, com.stone.proto.Servers.UnRegister.Builder.class);
    }

    public static com.google.protobuf.Parser<UnRegister> PARSER =
        new com.google.protobuf.AbstractParser<UnRegister>() {
      public UnRegister parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UnRegister(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UnRegister> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INFO_FIELD_NUMBER = 2;
    private com.stone.proto.Servers.ServerInfo info_;
    /**
     * <code>required .ServerInfo info = 2;</code>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ServerInfo info = 2;</code>
     */
    public com.stone.proto.Servers.ServerInfo getInfo() {
      return info_;
    }
    /**
     * <code>required .ServerInfo info = 2;</code>
     */
    public com.stone.proto.Servers.ServerInfoOrBuilder getInfoOrBuilder() {
      return info_;
    }

    private void initFields() {
      info_ = com.stone.proto.Servers.ServerInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, info_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, info_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.stone.proto.Servers.UnRegister parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.Servers.UnRegister parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.Servers.UnRegister parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.Servers.UnRegister parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.Servers.UnRegister parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.Servers.UnRegister parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.stone.proto.Servers.UnRegister parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.stone.proto.Servers.UnRegister parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.stone.proto.Servers.UnRegister parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.Servers.UnRegister parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.stone.proto.Servers.UnRegister prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UnRegister}
     *
     * <pre>
     * unRegister
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UnRegister)
        com.stone.proto.Servers.UnRegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stone.proto.Servers.internal_static_UnRegister_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stone.proto.Servers.internal_static_UnRegister_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stone.proto.Servers.UnRegister.class, com.stone.proto.Servers.UnRegister.Builder.class);
      }

      // Construct using com.stone.proto.Servers.UnRegister.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = com.stone.proto.Servers.ServerInfo.getDefaultInstance();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stone.proto.Servers.internal_static_UnRegister_descriptor;
      }

      public com.stone.proto.Servers.UnRegister getDefaultInstanceForType() {
        return com.stone.proto.Servers.UnRegister.getDefaultInstance();
      }

      public com.stone.proto.Servers.UnRegister build() {
        com.stone.proto.Servers.UnRegister result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stone.proto.Servers.UnRegister buildPartial() {
        com.stone.proto.Servers.UnRegister result = new com.stone.proto.Servers.UnRegister(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stone.proto.Servers.UnRegister) {
          return mergeFrom((com.stone.proto.Servers.UnRegister)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stone.proto.Servers.UnRegister other) {
        if (other == com.stone.proto.Servers.UnRegister.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInfo()) {
          
          return false;
        }
        if (!getInfo().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stone.proto.Servers.UnRegister parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stone.proto.Servers.UnRegister) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.stone.proto.Servers.ServerInfo info_ = com.stone.proto.Servers.ServerInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.stone.proto.Servers.ServerInfo, com.stone.proto.Servers.ServerInfo.Builder, com.stone.proto.Servers.ServerInfoOrBuilder> infoBuilder_;
      /**
       * <code>required .ServerInfo info = 2;</code>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ServerInfo info = 2;</code>
       */
      public com.stone.proto.Servers.ServerInfo getInfo() {
        if (infoBuilder_ == null) {
          return info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ServerInfo info = 2;</code>
       */
      public Builder setInfo(com.stone.proto.Servers.ServerInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ServerInfo info = 2;</code>
       */
      public Builder setInfo(
          com.stone.proto.Servers.ServerInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ServerInfo info = 2;</code>
       */
      public Builder mergeInfo(com.stone.proto.Servers.ServerInfo value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              info_ != com.stone.proto.Servers.ServerInfo.getDefaultInstance()) {
            info_ =
              com.stone.proto.Servers.ServerInfo.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ServerInfo info = 2;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = com.stone.proto.Servers.ServerInfo.getDefaultInstance();
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .ServerInfo info = 2;</code>
       */
      public com.stone.proto.Servers.ServerInfo.Builder getInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ServerInfo info = 2;</code>
       */
      public com.stone.proto.Servers.ServerInfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_;
        }
      }
      /**
       * <code>required .ServerInfo info = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.stone.proto.Servers.ServerInfo, com.stone.proto.Servers.ServerInfo.Builder, com.stone.proto.Servers.ServerInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.stone.proto.Servers.ServerInfo, com.stone.proto.Servers.ServerInfo.Builder, com.stone.proto.Servers.ServerInfoOrBuilder>(
                  getInfo(),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:UnRegister)
    }

    static {
      defaultInstance = new UnRegister(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UnRegister)
  }

  public interface GameRegisterToAgentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameRegisterToAgent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 sceneIds = 1;</code>
     */
    java.util.List<java.lang.Integer> getSceneIdsList();
    /**
     * <code>repeated int32 sceneIds = 1;</code>
     */
    int getSceneIdsCount();
    /**
     * <code>repeated int32 sceneIds = 1;</code>
     */
    int getSceneIds(int index);

    /**
     * <code>required .ServerInfo serverInfo = 2;</code>
     */
    boolean hasServerInfo();
    /**
     * <code>required .ServerInfo serverInfo = 2;</code>
     */
    com.stone.proto.Servers.ServerInfo getServerInfo();
    /**
     * <code>required .ServerInfo serverInfo = 2;</code>
     */
    com.stone.proto.Servers.ServerInfoOrBuilder getServerInfoOrBuilder();
  }
  /**
   * Protobuf type {@code GameRegisterToAgent}
   *
   * <pre>
   * game register to agent
   * </pre>
   */
  public static final class GameRegisterToAgent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GameRegisterToAgent)
      GameRegisterToAgentOrBuilder {
    // Use GameRegisterToAgent.newBuilder() to construct.
    private GameRegisterToAgent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameRegisterToAgent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameRegisterToAgent defaultInstance;
    public static GameRegisterToAgent getDefaultInstance() {
      return defaultInstance;
    }

    public GameRegisterToAgent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameRegisterToAgent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sceneIds_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              sceneIds_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                sceneIds_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                sceneIds_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              com.stone.proto.Servers.ServerInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = serverInfo_.toBuilder();
              }
              serverInfo_ = input.readMessage(com.stone.proto.Servers.ServerInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(serverInfo_);
                serverInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sceneIds_ = java.util.Collections.unmodifiableList(sceneIds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stone.proto.Servers.internal_static_GameRegisterToAgent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stone.proto.Servers.internal_static_GameRegisterToAgent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stone.proto.Servers.GameRegisterToAgent.class, com.stone.proto.Servers.GameRegisterToAgent.Builder.class);
    }

    public static com.google.protobuf.Parser<GameRegisterToAgent> PARSER =
        new com.google.protobuf.AbstractParser<GameRegisterToAgent>() {
      public GameRegisterToAgent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameRegisterToAgent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameRegisterToAgent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SCENEIDS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> sceneIds_;
    /**
     * <code>repeated int32 sceneIds = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getSceneIdsList() {
      return sceneIds_;
    }
    /**
     * <code>repeated int32 sceneIds = 1;</code>
     */
    public int getSceneIdsCount() {
      return sceneIds_.size();
    }
    /**
     * <code>repeated int32 sceneIds = 1;</code>
     */
    public int getSceneIds(int index) {
      return sceneIds_.get(index);
    }

    public static final int SERVERINFO_FIELD_NUMBER = 2;
    private com.stone.proto.Servers.ServerInfo serverInfo_;
    /**
     * <code>required .ServerInfo serverInfo = 2;</code>
     */
    public boolean hasServerInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ServerInfo serverInfo = 2;</code>
     */
    public com.stone.proto.Servers.ServerInfo getServerInfo() {
      return serverInfo_;
    }
    /**
     * <code>required .ServerInfo serverInfo = 2;</code>
     */
    public com.stone.proto.Servers.ServerInfoOrBuilder getServerInfoOrBuilder() {
      return serverInfo_;
    }

    private void initFields() {
      sceneIds_ = java.util.Collections.emptyList();
      serverInfo_ = com.stone.proto.Servers.ServerInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getServerInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < sceneIds_.size(); i++) {
        output.writeInt32(1, sceneIds_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, serverInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < sceneIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(sceneIds_.get(i));
        }
        size += dataSize;
        size += 1 * getSceneIdsList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, serverInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.stone.proto.Servers.GameRegisterToAgent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.Servers.GameRegisterToAgent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.Servers.GameRegisterToAgent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.Servers.GameRegisterToAgent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.Servers.GameRegisterToAgent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.Servers.GameRegisterToAgent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.stone.proto.Servers.GameRegisterToAgent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.stone.proto.Servers.GameRegisterToAgent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.stone.proto.Servers.GameRegisterToAgent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.Servers.GameRegisterToAgent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.stone.proto.Servers.GameRegisterToAgent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GameRegisterToAgent}
     *
     * <pre>
     * game register to agent
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameRegisterToAgent)
        com.stone.proto.Servers.GameRegisterToAgentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stone.proto.Servers.internal_static_GameRegisterToAgent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stone.proto.Servers.internal_static_GameRegisterToAgent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stone.proto.Servers.GameRegisterToAgent.class, com.stone.proto.Servers.GameRegisterToAgent.Builder.class);
      }

      // Construct using com.stone.proto.Servers.GameRegisterToAgent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getServerInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sceneIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        if (serverInfoBuilder_ == null) {
          serverInfo_ = com.stone.proto.Servers.ServerInfo.getDefaultInstance();
        } else {
          serverInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stone.proto.Servers.internal_static_GameRegisterToAgent_descriptor;
      }

      public com.stone.proto.Servers.GameRegisterToAgent getDefaultInstanceForType() {
        return com.stone.proto.Servers.GameRegisterToAgent.getDefaultInstance();
      }

      public com.stone.proto.Servers.GameRegisterToAgent build() {
        com.stone.proto.Servers.GameRegisterToAgent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stone.proto.Servers.GameRegisterToAgent buildPartial() {
        com.stone.proto.Servers.GameRegisterToAgent result = new com.stone.proto.Servers.GameRegisterToAgent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          sceneIds_ = java.util.Collections.unmodifiableList(sceneIds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.sceneIds_ = sceneIds_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        if (serverInfoBuilder_ == null) {
          result.serverInfo_ = serverInfo_;
        } else {
          result.serverInfo_ = serverInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stone.proto.Servers.GameRegisterToAgent) {
          return mergeFrom((com.stone.proto.Servers.GameRegisterToAgent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stone.proto.Servers.GameRegisterToAgent other) {
        if (other == com.stone.proto.Servers.GameRegisterToAgent.getDefaultInstance()) return this;
        if (!other.sceneIds_.isEmpty()) {
          if (sceneIds_.isEmpty()) {
            sceneIds_ = other.sceneIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSceneIdsIsMutable();
            sceneIds_.addAll(other.sceneIds_);
          }
          onChanged();
        }
        if (other.hasServerInfo()) {
          mergeServerInfo(other.getServerInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerInfo()) {
          
          return false;
        }
        if (!getServerInfo().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stone.proto.Servers.GameRegisterToAgent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stone.proto.Servers.GameRegisterToAgent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> sceneIds_ = java.util.Collections.emptyList();
      private void ensureSceneIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sceneIds_ = new java.util.ArrayList<java.lang.Integer>(sceneIds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 sceneIds = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getSceneIdsList() {
        return java.util.Collections.unmodifiableList(sceneIds_);
      }
      /**
       * <code>repeated int32 sceneIds = 1;</code>
       */
      public int getSceneIdsCount() {
        return sceneIds_.size();
      }
      /**
       * <code>repeated int32 sceneIds = 1;</code>
       */
      public int getSceneIds(int index) {
        return sceneIds_.get(index);
      }
      /**
       * <code>repeated int32 sceneIds = 1;</code>
       */
      public Builder setSceneIds(
          int index, int value) {
        ensureSceneIdsIsMutable();
        sceneIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 sceneIds = 1;</code>
       */
      public Builder addSceneIds(int value) {
        ensureSceneIdsIsMutable();
        sceneIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 sceneIds = 1;</code>
       */
      public Builder addAllSceneIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSceneIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sceneIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 sceneIds = 1;</code>
       */
      public Builder clearSceneIds() {
        sceneIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.stone.proto.Servers.ServerInfo serverInfo_ = com.stone.proto.Servers.ServerInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.stone.proto.Servers.ServerInfo, com.stone.proto.Servers.ServerInfo.Builder, com.stone.proto.Servers.ServerInfoOrBuilder> serverInfoBuilder_;
      /**
       * <code>required .ServerInfo serverInfo = 2;</code>
       */
      public boolean hasServerInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .ServerInfo serverInfo = 2;</code>
       */
      public com.stone.proto.Servers.ServerInfo getServerInfo() {
        if (serverInfoBuilder_ == null) {
          return serverInfo_;
        } else {
          return serverInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ServerInfo serverInfo = 2;</code>
       */
      public Builder setServerInfo(com.stone.proto.Servers.ServerInfo value) {
        if (serverInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serverInfo_ = value;
          onChanged();
        } else {
          serverInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .ServerInfo serverInfo = 2;</code>
       */
      public Builder setServerInfo(
          com.stone.proto.Servers.ServerInfo.Builder builderForValue) {
        if (serverInfoBuilder_ == null) {
          serverInfo_ = builderForValue.build();
          onChanged();
        } else {
          serverInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .ServerInfo serverInfo = 2;</code>
       */
      public Builder mergeServerInfo(com.stone.proto.Servers.ServerInfo value) {
        if (serverInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              serverInfo_ != com.stone.proto.Servers.ServerInfo.getDefaultInstance()) {
            serverInfo_ =
              com.stone.proto.Servers.ServerInfo.newBuilder(serverInfo_).mergeFrom(value).buildPartial();
          } else {
            serverInfo_ = value;
          }
          onChanged();
        } else {
          serverInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .ServerInfo serverInfo = 2;</code>
       */
      public Builder clearServerInfo() {
        if (serverInfoBuilder_ == null) {
          serverInfo_ = com.stone.proto.Servers.ServerInfo.getDefaultInstance();
          onChanged();
        } else {
          serverInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .ServerInfo serverInfo = 2;</code>
       */
      public com.stone.proto.Servers.ServerInfo.Builder getServerInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getServerInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ServerInfo serverInfo = 2;</code>
       */
      public com.stone.proto.Servers.ServerInfoOrBuilder getServerInfoOrBuilder() {
        if (serverInfoBuilder_ != null) {
          return serverInfoBuilder_.getMessageOrBuilder();
        } else {
          return serverInfo_;
        }
      }
      /**
       * <code>required .ServerInfo serverInfo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.stone.proto.Servers.ServerInfo, com.stone.proto.Servers.ServerInfo.Builder, com.stone.proto.Servers.ServerInfoOrBuilder> 
          getServerInfoFieldBuilder() {
        if (serverInfoBuilder_ == null) {
          serverInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.stone.proto.Servers.ServerInfo, com.stone.proto.Servers.ServerInfo.Builder, com.stone.proto.Servers.ServerInfoOrBuilder>(
                  getServerInfo(),
                  getParentForChildren(),
                  isClean());
          serverInfo_ = null;
        }
        return serverInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:GameRegisterToAgent)
    }

    static {
      defaultInstance = new GameRegisterToAgent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GameRegisterToAgent)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServerInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Register_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Register_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UnRegister_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UnRegister_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameRegisterToAgent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GameRegisterToAgent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Server.proto\"5\n\nServerInfo\022\031\n\004type\030\001 \002" +
      "(\0162\013.ServerType\022\014\n\004name\030\002 \002(\t\"%\n\010Registe" +
      "r\022\031\n\004info\030\001 \002(\0132\013.ServerInfo\"\'\n\nUnRegist" +
      "er\022\031\n\004info\030\002 \002(\0132\013.ServerInfo\"H\n\023GameReg" +
      "isterToAgent\022\020\n\010sceneIds\030\001 \003(\005\022\037\n\nserver" +
      "Info\030\002 \002(\0132\013.ServerInfo*>\n\nServerType\022\010\n" +
      "\004GATE\020\001\022\010\n\004GAME\020\002\022\t\n\005WORLD\020\003\022\006\n\002DB\020\004\022\t\n\005" +
      "CROSS\020\005B\032\n\017com.stone.protoB\007Servers"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ServerInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServerInfo_descriptor,
        new java.lang.String[] { "Type", "Name", });
    internal_static_Register_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Register_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Register_descriptor,
        new java.lang.String[] { "Info", });
    internal_static_UnRegister_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UnRegister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UnRegister_descriptor,
        new java.lang.String[] { "Info", });
    internal_static_GameRegisterToAgent_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GameRegisterToAgent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GameRegisterToAgent_descriptor,
        new java.lang.String[] { "SceneIds", "ServerInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
