// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Entity.proto

package com.stone.proto.entity;

public final class Entities {
  private Entities() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HumanItemDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HumanItemData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 humanGuid = 1;</code>
     */
    boolean hasHumanGuid();
    /**
     * <code>required int64 humanGuid = 1;</code>
     */
    long getHumanGuid();

    /**
     * <code>required .Item item = 2;</code>
     */
    boolean hasItem();
    /**
     * <code>required .Item item = 2;</code>
     */
    com.stone.proto.common.Commons.Item getItem();
    /**
     * <code>required .Item item = 2;</code>
     */
    com.stone.proto.common.Commons.ItemOrBuilder getItemOrBuilder();
  }
  /**
   * Protobuf type {@code HumanItemData}
   *
   * <pre>
   * ItemEntity
   * </pre>
   */
  public static final class HumanItemData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HumanItemData)
      HumanItemDataOrBuilder {
    // Use HumanItemData.newBuilder() to construct.
    private HumanItemData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HumanItemData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HumanItemData defaultInstance;
    public static HumanItemData getDefaultInstance() {
      return defaultInstance;
    }

    public HumanItemData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HumanItemData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              humanGuid_ = input.readInt64();
              break;
            }
            case 18: {
              com.stone.proto.common.Commons.Item.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = item_.toBuilder();
              }
              item_ = input.readMessage(com.stone.proto.common.Commons.Item.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(item_);
                item_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stone.proto.entity.Entities.internal_static_HumanItemData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stone.proto.entity.Entities.internal_static_HumanItemData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stone.proto.entity.Entities.HumanItemData.class, com.stone.proto.entity.Entities.HumanItemData.Builder.class);
    }

    public static com.google.protobuf.Parser<HumanItemData> PARSER =
        new com.google.protobuf.AbstractParser<HumanItemData>() {
      public HumanItemData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HumanItemData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HumanItemData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HUMANGUID_FIELD_NUMBER = 1;
    private long humanGuid_;
    /**
     * <code>required int64 humanGuid = 1;</code>
     */
    public boolean hasHumanGuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 humanGuid = 1;</code>
     */
    public long getHumanGuid() {
      return humanGuid_;
    }

    public static final int ITEM_FIELD_NUMBER = 2;
    private com.stone.proto.common.Commons.Item item_;
    /**
     * <code>required .Item item = 2;</code>
     */
    public boolean hasItem() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Item item = 2;</code>
     */
    public com.stone.proto.common.Commons.Item getItem() {
      return item_;
    }
    /**
     * <code>required .Item item = 2;</code>
     */
    public com.stone.proto.common.Commons.ItemOrBuilder getItemOrBuilder() {
      return item_;
    }

    private void initFields() {
      humanGuid_ = 0L;
      item_ = com.stone.proto.common.Commons.Item.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHumanGuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasItem()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getItem().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, humanGuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, item_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, humanGuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, item_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.stone.proto.entity.Entities.HumanItemData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.entity.Entities.HumanItemData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.entity.Entities.HumanItemData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.entity.Entities.HumanItemData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.entity.Entities.HumanItemData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.entity.Entities.HumanItemData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.stone.proto.entity.Entities.HumanItemData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.stone.proto.entity.Entities.HumanItemData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.stone.proto.entity.Entities.HumanItemData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.entity.Entities.HumanItemData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.stone.proto.entity.Entities.HumanItemData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HumanItemData}
     *
     * <pre>
     * ItemEntity
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HumanItemData)
        com.stone.proto.entity.Entities.HumanItemDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stone.proto.entity.Entities.internal_static_HumanItemData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stone.proto.entity.Entities.internal_static_HumanItemData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stone.proto.entity.Entities.HumanItemData.class, com.stone.proto.entity.Entities.HumanItemData.Builder.class);
      }

      // Construct using com.stone.proto.entity.Entities.HumanItemData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        humanGuid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (itemBuilder_ == null) {
          item_ = com.stone.proto.common.Commons.Item.getDefaultInstance();
        } else {
          itemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stone.proto.entity.Entities.internal_static_HumanItemData_descriptor;
      }

      public com.stone.proto.entity.Entities.HumanItemData getDefaultInstanceForType() {
        return com.stone.proto.entity.Entities.HumanItemData.getDefaultInstance();
      }

      public com.stone.proto.entity.Entities.HumanItemData build() {
        com.stone.proto.entity.Entities.HumanItemData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stone.proto.entity.Entities.HumanItemData buildPartial() {
        com.stone.proto.entity.Entities.HumanItemData result = new com.stone.proto.entity.Entities.HumanItemData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.humanGuid_ = humanGuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (itemBuilder_ == null) {
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stone.proto.entity.Entities.HumanItemData) {
          return mergeFrom((com.stone.proto.entity.Entities.HumanItemData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stone.proto.entity.Entities.HumanItemData other) {
        if (other == com.stone.proto.entity.Entities.HumanItemData.getDefaultInstance()) return this;
        if (other.hasHumanGuid()) {
          setHumanGuid(other.getHumanGuid());
        }
        if (other.hasItem()) {
          mergeItem(other.getItem());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHumanGuid()) {
          
          return false;
        }
        if (!hasItem()) {
          
          return false;
        }
        if (!getItem().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stone.proto.entity.Entities.HumanItemData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stone.proto.entity.Entities.HumanItemData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long humanGuid_ ;
      /**
       * <code>required int64 humanGuid = 1;</code>
       */
      public boolean hasHumanGuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 humanGuid = 1;</code>
       */
      public long getHumanGuid() {
        return humanGuid_;
      }
      /**
       * <code>required int64 humanGuid = 1;</code>
       */
      public Builder setHumanGuid(long value) {
        bitField0_ |= 0x00000001;
        humanGuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 humanGuid = 1;</code>
       */
      public Builder clearHumanGuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        humanGuid_ = 0L;
        onChanged();
        return this;
      }

      private com.stone.proto.common.Commons.Item item_ = com.stone.proto.common.Commons.Item.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.stone.proto.common.Commons.Item, com.stone.proto.common.Commons.Item.Builder, com.stone.proto.common.Commons.ItemOrBuilder> itemBuilder_;
      /**
       * <code>required .Item item = 2;</code>
       */
      public boolean hasItem() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Item item = 2;</code>
       */
      public com.stone.proto.common.Commons.Item getItem() {
        if (itemBuilder_ == null) {
          return item_;
        } else {
          return itemBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Item item = 2;</code>
       */
      public Builder setItem(com.stone.proto.common.Commons.Item value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          item_ = value;
          onChanged();
        } else {
          itemBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Item item = 2;</code>
       */
      public Builder setItem(
          com.stone.proto.common.Commons.Item.Builder builderForValue) {
        if (itemBuilder_ == null) {
          item_ = builderForValue.build();
          onChanged();
        } else {
          itemBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Item item = 2;</code>
       */
      public Builder mergeItem(com.stone.proto.common.Commons.Item value) {
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              item_ != com.stone.proto.common.Commons.Item.getDefaultInstance()) {
            item_ =
              com.stone.proto.common.Commons.Item.newBuilder(item_).mergeFrom(value).buildPartial();
          } else {
            item_ = value;
          }
          onChanged();
        } else {
          itemBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Item item = 2;</code>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = com.stone.proto.common.Commons.Item.getDefaultInstance();
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .Item item = 2;</code>
       */
      public com.stone.proto.common.Commons.Item.Builder getItemBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getItemFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Item item = 2;</code>
       */
      public com.stone.proto.common.Commons.ItemOrBuilder getItemOrBuilder() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilder();
        } else {
          return item_;
        }
      }
      /**
       * <code>required .Item item = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.stone.proto.common.Commons.Item, com.stone.proto.common.Commons.Item.Builder, com.stone.proto.common.Commons.ItemOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.stone.proto.common.Commons.Item, com.stone.proto.common.Commons.Item.Builder, com.stone.proto.common.Commons.ItemOrBuilder>(
                  getItem(),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:HumanItemData)
    }

    static {
      defaultInstance = new HumanItemData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HumanItemData)
  }

  public interface HumanDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HumanData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 guid = 1;</code>
     */
    boolean hasGuid();
    /**
     * <code>required int64 guid = 1;</code>
     */
    long getGuid();

    /**
     * <code>repeated .HumanItemData humanItems = 2;</code>
     *
     * <pre>
     * item
     * </pre>
     */
    java.util.List<com.stone.proto.entity.Entities.HumanItemData> 
        getHumanItemsList();
    /**
     * <code>repeated .HumanItemData humanItems = 2;</code>
     *
     * <pre>
     * item
     * </pre>
     */
    com.stone.proto.entity.Entities.HumanItemData getHumanItems(int index);
    /**
     * <code>repeated .HumanItemData humanItems = 2;</code>
     *
     * <pre>
     * item
     * </pre>
     */
    int getHumanItemsCount();
    /**
     * <code>repeated .HumanItemData humanItems = 2;</code>
     *
     * <pre>
     * item
     * </pre>
     */
    java.util.List<? extends com.stone.proto.entity.Entities.HumanItemDataOrBuilder> 
        getHumanItemsOrBuilderList();
    /**
     * <code>repeated .HumanItemData humanItems = 2;</code>
     *
     * <pre>
     * item
     * </pre>
     */
    com.stone.proto.entity.Entities.HumanItemDataOrBuilder getHumanItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code HumanData}
   *
   * <pre>
   * HumanEntity
   * </pre>
   */
  public static final class HumanData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HumanData)
      HumanDataOrBuilder {
    // Use HumanData.newBuilder() to construct.
    private HumanData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HumanData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HumanData defaultInstance;
    public static HumanData getDefaultInstance() {
      return defaultInstance;
    }

    public HumanData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HumanData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              guid_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                humanItems_ = new java.util.ArrayList<com.stone.proto.entity.Entities.HumanItemData>();
                mutable_bitField0_ |= 0x00000002;
              }
              humanItems_.add(input.readMessage(com.stone.proto.entity.Entities.HumanItemData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          humanItems_ = java.util.Collections.unmodifiableList(humanItems_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stone.proto.entity.Entities.internal_static_HumanData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stone.proto.entity.Entities.internal_static_HumanData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stone.proto.entity.Entities.HumanData.class, com.stone.proto.entity.Entities.HumanData.Builder.class);
    }

    public static com.google.protobuf.Parser<HumanData> PARSER =
        new com.google.protobuf.AbstractParser<HumanData>() {
      public HumanData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HumanData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HumanData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int GUID_FIELD_NUMBER = 1;
    private long guid_;
    /**
     * <code>required int64 guid = 1;</code>
     */
    public boolean hasGuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 guid = 1;</code>
     */
    public long getGuid() {
      return guid_;
    }

    public static final int HUMANITEMS_FIELD_NUMBER = 2;
    private java.util.List<com.stone.proto.entity.Entities.HumanItemData> humanItems_;
    /**
     * <code>repeated .HumanItemData humanItems = 2;</code>
     *
     * <pre>
     * item
     * </pre>
     */
    public java.util.List<com.stone.proto.entity.Entities.HumanItemData> getHumanItemsList() {
      return humanItems_;
    }
    /**
     * <code>repeated .HumanItemData humanItems = 2;</code>
     *
     * <pre>
     * item
     * </pre>
     */
    public java.util.List<? extends com.stone.proto.entity.Entities.HumanItemDataOrBuilder> 
        getHumanItemsOrBuilderList() {
      return humanItems_;
    }
    /**
     * <code>repeated .HumanItemData humanItems = 2;</code>
     *
     * <pre>
     * item
     * </pre>
     */
    public int getHumanItemsCount() {
      return humanItems_.size();
    }
    /**
     * <code>repeated .HumanItemData humanItems = 2;</code>
     *
     * <pre>
     * item
     * </pre>
     */
    public com.stone.proto.entity.Entities.HumanItemData getHumanItems(int index) {
      return humanItems_.get(index);
    }
    /**
     * <code>repeated .HumanItemData humanItems = 2;</code>
     *
     * <pre>
     * item
     * </pre>
     */
    public com.stone.proto.entity.Entities.HumanItemDataOrBuilder getHumanItemsOrBuilder(
        int index) {
      return humanItems_.get(index);
    }

    private void initFields() {
      guid_ = 0L;
      humanItems_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasGuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getHumanItemsCount(); i++) {
        if (!getHumanItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, guid_);
      }
      for (int i = 0; i < humanItems_.size(); i++) {
        output.writeMessage(2, humanItems_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, guid_);
      }
      for (int i = 0; i < humanItems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, humanItems_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.stone.proto.entity.Entities.HumanData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.entity.Entities.HumanData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.entity.Entities.HumanData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.entity.Entities.HumanData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.entity.Entities.HumanData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.entity.Entities.HumanData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.stone.proto.entity.Entities.HumanData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.stone.proto.entity.Entities.HumanData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.stone.proto.entity.Entities.HumanData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.entity.Entities.HumanData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.stone.proto.entity.Entities.HumanData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HumanData}
     *
     * <pre>
     * HumanEntity
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HumanData)
        com.stone.proto.entity.Entities.HumanDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stone.proto.entity.Entities.internal_static_HumanData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stone.proto.entity.Entities.internal_static_HumanData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stone.proto.entity.Entities.HumanData.class, com.stone.proto.entity.Entities.HumanData.Builder.class);
      }

      // Construct using com.stone.proto.entity.Entities.HumanData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHumanItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        guid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (humanItemsBuilder_ == null) {
          humanItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          humanItemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stone.proto.entity.Entities.internal_static_HumanData_descriptor;
      }

      public com.stone.proto.entity.Entities.HumanData getDefaultInstanceForType() {
        return com.stone.proto.entity.Entities.HumanData.getDefaultInstance();
      }

      public com.stone.proto.entity.Entities.HumanData build() {
        com.stone.proto.entity.Entities.HumanData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stone.proto.entity.Entities.HumanData buildPartial() {
        com.stone.proto.entity.Entities.HumanData result = new com.stone.proto.entity.Entities.HumanData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.guid_ = guid_;
        if (humanItemsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            humanItems_ = java.util.Collections.unmodifiableList(humanItems_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.humanItems_ = humanItems_;
        } else {
          result.humanItems_ = humanItemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stone.proto.entity.Entities.HumanData) {
          return mergeFrom((com.stone.proto.entity.Entities.HumanData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stone.proto.entity.Entities.HumanData other) {
        if (other == com.stone.proto.entity.Entities.HumanData.getDefaultInstance()) return this;
        if (other.hasGuid()) {
          setGuid(other.getGuid());
        }
        if (humanItemsBuilder_ == null) {
          if (!other.humanItems_.isEmpty()) {
            if (humanItems_.isEmpty()) {
              humanItems_ = other.humanItems_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureHumanItemsIsMutable();
              humanItems_.addAll(other.humanItems_);
            }
            onChanged();
          }
        } else {
          if (!other.humanItems_.isEmpty()) {
            if (humanItemsBuilder_.isEmpty()) {
              humanItemsBuilder_.dispose();
              humanItemsBuilder_ = null;
              humanItems_ = other.humanItems_;
              bitField0_ = (bitField0_ & ~0x00000002);
              humanItemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHumanItemsFieldBuilder() : null;
            } else {
              humanItemsBuilder_.addAllMessages(other.humanItems_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGuid()) {
          
          return false;
        }
        for (int i = 0; i < getHumanItemsCount(); i++) {
          if (!getHumanItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stone.proto.entity.Entities.HumanData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stone.proto.entity.Entities.HumanData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long guid_ ;
      /**
       * <code>required int64 guid = 1;</code>
       */
      public boolean hasGuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 guid = 1;</code>
       */
      public long getGuid() {
        return guid_;
      }
      /**
       * <code>required int64 guid = 1;</code>
       */
      public Builder setGuid(long value) {
        bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 guid = 1;</code>
       */
      public Builder clearGuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        guid_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.stone.proto.entity.Entities.HumanItemData> humanItems_ =
        java.util.Collections.emptyList();
      private void ensureHumanItemsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          humanItems_ = new java.util.ArrayList<com.stone.proto.entity.Entities.HumanItemData>(humanItems_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.stone.proto.entity.Entities.HumanItemData, com.stone.proto.entity.Entities.HumanItemData.Builder, com.stone.proto.entity.Entities.HumanItemDataOrBuilder> humanItemsBuilder_;

      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public java.util.List<com.stone.proto.entity.Entities.HumanItemData> getHumanItemsList() {
        if (humanItemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(humanItems_);
        } else {
          return humanItemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public int getHumanItemsCount() {
        if (humanItemsBuilder_ == null) {
          return humanItems_.size();
        } else {
          return humanItemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public com.stone.proto.entity.Entities.HumanItemData getHumanItems(int index) {
        if (humanItemsBuilder_ == null) {
          return humanItems_.get(index);
        } else {
          return humanItemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public Builder setHumanItems(
          int index, com.stone.proto.entity.Entities.HumanItemData value) {
        if (humanItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHumanItemsIsMutable();
          humanItems_.set(index, value);
          onChanged();
        } else {
          humanItemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public Builder setHumanItems(
          int index, com.stone.proto.entity.Entities.HumanItemData.Builder builderForValue) {
        if (humanItemsBuilder_ == null) {
          ensureHumanItemsIsMutable();
          humanItems_.set(index, builderForValue.build());
          onChanged();
        } else {
          humanItemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public Builder addHumanItems(com.stone.proto.entity.Entities.HumanItemData value) {
        if (humanItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHumanItemsIsMutable();
          humanItems_.add(value);
          onChanged();
        } else {
          humanItemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public Builder addHumanItems(
          int index, com.stone.proto.entity.Entities.HumanItemData value) {
        if (humanItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHumanItemsIsMutable();
          humanItems_.add(index, value);
          onChanged();
        } else {
          humanItemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public Builder addHumanItems(
          com.stone.proto.entity.Entities.HumanItemData.Builder builderForValue) {
        if (humanItemsBuilder_ == null) {
          ensureHumanItemsIsMutable();
          humanItems_.add(builderForValue.build());
          onChanged();
        } else {
          humanItemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public Builder addHumanItems(
          int index, com.stone.proto.entity.Entities.HumanItemData.Builder builderForValue) {
        if (humanItemsBuilder_ == null) {
          ensureHumanItemsIsMutable();
          humanItems_.add(index, builderForValue.build());
          onChanged();
        } else {
          humanItemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public Builder addAllHumanItems(
          java.lang.Iterable<? extends com.stone.proto.entity.Entities.HumanItemData> values) {
        if (humanItemsBuilder_ == null) {
          ensureHumanItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, humanItems_);
          onChanged();
        } else {
          humanItemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public Builder clearHumanItems() {
        if (humanItemsBuilder_ == null) {
          humanItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          humanItemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public Builder removeHumanItems(int index) {
        if (humanItemsBuilder_ == null) {
          ensureHumanItemsIsMutable();
          humanItems_.remove(index);
          onChanged();
        } else {
          humanItemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public com.stone.proto.entity.Entities.HumanItemData.Builder getHumanItemsBuilder(
          int index) {
        return getHumanItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public com.stone.proto.entity.Entities.HumanItemDataOrBuilder getHumanItemsOrBuilder(
          int index) {
        if (humanItemsBuilder_ == null) {
          return humanItems_.get(index);  } else {
          return humanItemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public java.util.List<? extends com.stone.proto.entity.Entities.HumanItemDataOrBuilder> 
           getHumanItemsOrBuilderList() {
        if (humanItemsBuilder_ != null) {
          return humanItemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(humanItems_);
        }
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public com.stone.proto.entity.Entities.HumanItemData.Builder addHumanItemsBuilder() {
        return getHumanItemsFieldBuilder().addBuilder(
            com.stone.proto.entity.Entities.HumanItemData.getDefaultInstance());
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public com.stone.proto.entity.Entities.HumanItemData.Builder addHumanItemsBuilder(
          int index) {
        return getHumanItemsFieldBuilder().addBuilder(
            index, com.stone.proto.entity.Entities.HumanItemData.getDefaultInstance());
      }
      /**
       * <code>repeated .HumanItemData humanItems = 2;</code>
       *
       * <pre>
       * item
       * </pre>
       */
      public java.util.List<com.stone.proto.entity.Entities.HumanItemData.Builder> 
           getHumanItemsBuilderList() {
        return getHumanItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.stone.proto.entity.Entities.HumanItemData, com.stone.proto.entity.Entities.HumanItemData.Builder, com.stone.proto.entity.Entities.HumanItemDataOrBuilder> 
          getHumanItemsFieldBuilder() {
        if (humanItemsBuilder_ == null) {
          humanItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.stone.proto.entity.Entities.HumanItemData, com.stone.proto.entity.Entities.HumanItemData.Builder, com.stone.proto.entity.Entities.HumanItemDataOrBuilder>(
                  humanItems_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          humanItems_ = null;
        }
        return humanItemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:HumanData)
    }

    static {
      defaultInstance = new HumanData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HumanData)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HumanItemData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HumanItemData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HumanData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HumanData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Entity.proto\032\014Common.proto\"7\n\rHumanIte" +
      "mData\022\021\n\thumanGuid\030\001 \002(\003\022\023\n\004item\030\002 \002(\0132\005" +
      ".Item\"=\n\tHumanData\022\014\n\004guid\030\001 \002(\003\022\"\n\nhuma" +
      "nItems\030\002 \003(\0132\016.HumanItemDataB\"\n\026com.ston" +
      "e.proto.entityB\010Entities"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stone.proto.common.Commons.getDescriptor(),
        }, assigner);
    internal_static_HumanItemData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HumanItemData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HumanItemData_descriptor,
        new java.lang.String[] { "HumanGuid", "Item", });
    internal_static_HumanData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HumanData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HumanData_descriptor,
        new java.lang.String[] { "Guid", "HumanItems", });
    com.stone.proto.common.Commons.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
