package com.stupidbird.game.template;

import com.stupidbird.core.template.BaseTemplate;
import com.stupidbird.core.template.TemplateService.XmlResource;


/**
 * The template of ItemLevelUpTemplate( 物品升级模版 );<br>
 *
 * Auto generated by tools, do not modified;
 *
 * @author crazyjohn
 *
 */
@XmlResource(file = "xml/ItemLevelUpTemplate.xml")
public class ItemLevelUpTemplate extends BaseTemplate {
	/** 等级s */
	@Id
	protected int level;
	/** 消耗货币s */
	protected int costCoin;
	/** descs */
	protected String desc;

	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public int getCostCoin() {
		return costCoin;
	}

	public void setCostCoin(int costCoin) {
		this.costCoin = costCoin;
	}

	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}